---
Name: fluentrouting
---
SilverStripe\Control\Director:
  extensions:
    FluentDirectorExtension: TractorCow\Fluent\Extension\FluentDirectorExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        InitStateMiddleware: %$TractorCow\Fluent\Middleware\InitStateMiddleware
        HandleRedirectMiddleware: %$TractorCow\Fluent\Middleware\HandleRedirectMiddleware
